CREATE DATABASE OffersDb

CREATE TABLE [dbo].[ArtistTitle] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [url]          NVARCHAR (MAX)   NOT NULL,
    [price]        INT              NOT NULL,
    [currencyId]   NCHAR (10)       NOT NULL,
    [categoryId]   INT              NOT NULL,
    [picture]      NVARCHAR (MAX)   NOT NULL,
    [delivery]     NCHAR (10)       NOT NULL,
    [artist]       NVARCHAR (50)    NULL,
    [title]        NVARCHAR (MAX)   NOT NULL,
    [year]         NCHAR (10)       NOT NULL,
    [media]        NCHAR (10)       NOT NULL,
    [description]  NVARCHAR (MAX)   NOT NULL,
    [starring]     NVARCHAR (MAX)   NULL,
    [director]     NVARCHAR (50)    NULL,
    [originalName] NVARCHAR (50)    NULL,
    [country]      NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[Audiobooks] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [url]              NVARCHAR (MAX)   NOT NULL,
    [price]            INT              NOT NULL,
    [currencyId]       NCHAR (10)       NOT NULL,
    [categoryId]       INT              NOT NULL,
    [picture]          NVARCHAR (MAX)   NOT NULL,
    [author]           NVARCHAR (50)    NULL,
    [name]             NVARCHAR (50)    NULL,
    [publisher]        NVARCHAR (50)    NULL,
    [year]             NCHAR (10)       NULL,
    [ISBN]             NVARCHAR (50)    NULL,
    [language]         NCHAR (10)       NULL,
    [performed_by]     NVARCHAR (50)    NULL,
    [performance_type] NCHAR (10)       NULL,
    [storage]          NCHAR (10)       NULL,
    [format]           NCHAR (10)       NULL,
    [recording_length] NCHAR (10)       NULL,
    [description]      NVARCHAR (MAX)   NULL,
    [downloadable]     NCHAR (10)       NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
CREATE TABLE [dbo].[Books] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [url]                 NVARCHAR (MAX)   NOT NULL,
    [price]               INT              NOT NULL,
    [currencyId]          NCHAR (10)       NOT NULL,
    [categoryId]          INT              NOT NULL,
    [picture]             NVARCHAR (MAX)   NOT NULL,
    [delivery]            NCHAR (10)       NOT NULL,
    [local_delivery_cost] INT              NOT NULL,
    [author]              NVARCHAR (50)    NULL,
    [name]                NVARCHAR (50)    NULL,
    [publisher]           NVARCHAR (50)    NULL,
    [series]              NVARCHAR (50)    NULL,
    [year]                NCHAR (10)       NULL,
    [ISBN]                NVARCHAR (50)    NULL,
    [volume]              INT              NULL,
    [part]                INT              NULL,
    [language]            NCHAR (10)       NULL,
    [binding]             NCHAR (10)       NULL,
    [page_extent]         INT              NULL,
    [description]         NVARCHAR (MAX)   NULL,
    [downloadable]        NCHAR (10)       NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[EventTickets] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [url]                 NVARCHAR (MAX)   NOT NULL,
    [price]               INT              NOT NULL,
    [currencyId]          NCHAR (10)       NOT NULL,
    [categoryId]          INT              NOT NULL,
    [picture]             NVARCHAR (MAX)   NOT NULL,
    [delivery]            NCHAR (10)       NOT NULL,
    [local_delivery_cost] INT              NOT NULL,
    [name]                NVARCHAR (MAX)   NULL,
    [place]               NVARCHAR (MAX)   NULL,
    [hall]                NVARCHAR (50)    NULL,
    [hall_part]           NVARCHAR (50)    NULL,
    [date]                NVARCHAR (50)    NULL,
    [is_premiere]         INT              NULL,
    [is_kids]             INT              NULL,
    [description]         NVARCHAR (MAX)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

CREATE TABLE [dbo].[Tours] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [url]                 NVARCHAR (MAX)   NOT NULL,
    [price]               INT              NOT NULL,
    [currencyId]          NCHAR (10)       NOT NULL,
    [categoryId]          INT              NOT NULL,
    [picture]             NVARCHAR (MAX)   NOT NULL,
    [delivery]            NCHAR (10)       NOT NULL,
    [local_delivery_cost] INT              NOT NULL,
    [description]         NVARCHAR (MAX)   NULL,
    [worldRegion]         NVARCHAR (50)    NULL,
    [country]             NVARCHAR (50)    NULL,
    [region]              NVARCHAR (50)    NULL,
    [days]                INT              NULL,
    [dataTour]            DATE             NULL,
    [name]                NVARCHAR (50)    NULL,
    [hotel_stars]         NCHAR (10)       NULL,
    [room]                NCHAR (10)       NULL,
    [meal]                NCHAR (10)       NULL,
    [included]            NVARCHAR (MAX)   NULL,
    [transport]           NCHAR (10)       NULL,
    [dataTour2]           DATE             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
CREATE TABLE [dbo].[VendorModels] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [url]                   NVARCHAR (MAX)   NOT NULL,
    [price]                 INT              NOT NULL,
    [currencyId]            NCHAR (10)       NOT NULL,
    [categoryId]            INT              NOT NULL,
    [picture]               NVARCHAR (MAX)   NOT NULL,
    [delivery]              NCHAR (10)       NOT NULL,
    [local_delivery_cost]   INT              NOT NULL,
    [typePrefix]            NVARCHAR (50)    NULL,
    [vendor]                NVARCHAR (50)    NULL,
    [vendorCode]            NCHAR (10)       NULL,
    [model]                 NVARCHAR (50)    NULL,
    [description]           NVARCHAR (MAX)   NULL,
    [manufacturer_warranty] NCHAR (10)       NULL,
    [country_of_origin]     NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);
